# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar_client_side_validations}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Cardarella"]
  s.date = %q{2010-05-24}
  s.description = %q{ActiveRecord 2.x Client Side Validations}
  s.email = %q{cardarellab@dnc.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ar_client_side_validations.gemspec",
     "assets/javascript/ar_client_side_validations.js",
     "lib/adapters/active_model.rb",
     "lib/adapters/active_record_2.rb",
     "lib/client_side_validations.rb",
     "spec/active_model_3_spec.rb",
     "spec/active_record_2_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/required_gems.rb",
     "tasks/spec.rake"
  ]
  s.homepage = %q{http://github.com/dnclabs/ar_client_side_validations}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Client Side Validation}
  s.test_files = [
    "spec/active_model_3_spec.rb",
     "spec/active_record_2_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/required_gems.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<validation_reflection>, [">= 0.3.6"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<validation_reflection>, [">= 0.3.6"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<validation_reflection>, [">= 0.3.6"])
  end
end

